# Site settings
title: My Tech Blog
description: A blog about programming and technology
author: Your Name

# GitHub Pages settings (these are crucial for proper deployment)
baseurl: ""  # Changed from "/test-blog" to "" for root domain
url: "https://KRana17.github.io"  # Required - your GitHub Pages URL

# Theme settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /:categories/:year/:month/:day/:title/

# Default settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Khevna Rana"
